version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: runmymind/docker-android-sdk:latest
    working_directory: ~/KotlinCalculator
    steps:
      - checkout
      - run: ./gradlew
