version: 2
jobs:
  build:
    docker:
      - image: beevelop/android:latest
    working_directory: ~/KotlinCalculator
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - v1-myapp-
      - run: ./gradlew assembleDebug --console plain
      - save_cache:
          key: v1-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - /home/ubuntu/.gradle
            - ~/KotlinCalculator/.gradle
      - store_artifacts:
          path: /app/build/outputs/apk/debug/
          destination: build
