version: 2
jobs:
  build:
    docker:
      - image: beevelop/android:latest
    working_directory: ~/KotlinCalculator
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - v1-myapp-
      - run: ./gradlew
      - save_cache:
          key: v1-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - /home/ubuntu/.gradle
      - run: ./gradlew assembleDebug
