version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android
    working_directory: ~/KotlinCalculator
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run: ./gradlew clean build --project-cache-dir ~/.gradle --console plain
      - save_cache:
          key: v2-myapp-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
      - store_artifacts:
          path: ~/KotlinCalculator/app/build/outputs/apk/**/
          destination: build
